//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public citas()
        {
            this.citasProgramadas = new HashSet<citasProgramadas>();
        }
    
        public long codigoCitas { get; set; }
        public string asunto { get; set; }
        public string descripsion { get; set; }
        public Nullable<System.DateTime> horaInicio { get; set; }
        public Nullable<System.DateTime> horafin { get; set; }
        public string temaColor { get; set; }
        public Nullable<bool> esTodoElDia { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citasProgramadas> citasProgramadas { get; set; }
    }
}
