//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class citasProgramadas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public citasProgramadas()
        {
            this.paciente = new HashSet<paciente>();
        }
    
        public long codigoCitaProgramadas { get; set; }
        public long codigoCitasFK { get; set; }
        public long codigoPacienteFK { get; set; }
        public long codigoDoctorFK { get; set; }
        public string padecimiento { get; set; }
        public string tratamiento { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual citas citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paciente> paciente { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual paciente paciente1 { get; set; }
    }
}
