//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class citasProgramadas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public citasProgramadas()
        {
            this.paciente = new HashSet<paciente>();
            this.expediente = new HashSet<expediente>();
        }
    
        public long codigoCitaProgramadas { get; set; }
        public long codigoCitasFK { get; set; }
        public long codigoPacienteFK { get; set; }
        public long codigoDoctorFK { get; set; }
        public string padecimiento { get; set; }
        public string tratamiento { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual citas citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paciente> paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expediente> expediente { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual paciente paciente1 { get; set; }
    }
}
