//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paciente()
        {
            this.citasProgramadas1 = new HashSet<citasProgramadas>();
            this.expediente1 = new HashSet<expediente>();
        }
    
        public long codigoPaciente { get; set; }
        public Nullable<long> codigoPersonaFK { get; set; }
        public Nullable<long> codigoCitaProgramadaFK { get; set; }
        public Nullable<long> codigoExpedienteFK { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual citasProgramadas citasProgramadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citasProgramadas> citasProgramadas1 { get; set; }
        public virtual expediente expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expediente> expediente1 { get; set; }
        public virtual persona persona { get; set; }
    }
}
