//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteCitas
    {
        public long codigoreporteCitas { get; set; }
        public Nullable<long> codigoExpedienteFK { get; set; }
    
        public virtual expediente expediente { get; set; }
    }
}
