//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public long codigoUsuario { get; set; }
        public string contrasena { get; set; }
        public Nullable<long> codigoPersonaFK { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
